### ISSUE TITLE
include plist.h has duplicate definitions

### ISSUE THREAD

**Issue by elekven-m** [libimobiledevice/libimobiledevice-glue#31]
libplist's plist.h has been modified, it now defines PLIST_FORMAT_<type> enums. These get redefined in libimobiledevice-glue's utils.h with different values. Build under mingw fails. Because libimobiledevice-glue's utils.h now includes plist.h, the duplicate definitions in utils.h should be deleted.

**Comment by nikias** [comment]
Yes I know, I am working on updating everything

**Comment by ximbal** [comment]
Hi, any updates on this one?

Thank you

**Comment by nikias** [comment]
This has been resolved.
