### ISSUE TITLE
git-version-gen has not been included in the tarball

### ISSUE THREAD

**Issue by heitbaum** [libimobiledevice/libimobiledevice-glue#32]
git-version-gen has not been included in the tarball and causes the build to error. 

Even after copying this file inplace - getting the following build error.

`configure:error: PACKAGE_VERSION is not defined. Make sure to configure a source tree checked out from git or that .tarball-version is present. `

**Comment by nikias** [comment]
Oh thanks for the reminder... obviously this breaks. Also it needs a .tarball-version file 🤦‍♂️

**Comment by nikias** [comment]
Updated the release tarball and fixed in in git.

**Comment by heitbaum** [comment]
> Updated the release tarball and fixed in in git.

Tested and working 👍

**Comment by dingziyang** [comment]
**I don't have a clone, I downloaded it directly because the internet is very slow.**
where is the .tarball-version file? whatever in master or tag, I cannot found it.
