### ISSUE TITLE
configure: error: Package requirements (libplist-2.0 >= 2.3.0) were not met:  Requested 'libplist-2.0 >= 2.3.0' but version of libplist is 2.2.0

### ISSUE THREAD

**Issue by snoopyonline78** [libimobiledevice/libimobiledevice-glue#39]
Dear community, i don't understand the error. a libplist between 2.0 and 2.3.0 is required, and i habe 2.2.0 installed. 

Why do i get the error?

Thanks a lot for your patience.

Kindly Regards

**Comment by nikias** [comment]
The error means you need 2.3.0 or later. Anyway, not a bug.
