### ISSUE TITLE
Move common code from `idevicerestore` to the glue library

### ISSUE THREAD

**Issue by rickmark** [libimobiledevice/libimobiledevice-glue#4]
In preparations for refactoring the `idevicerestore` program, I've begun to grab any code that is not restore specific but nonetheless needs to be moved to the glue library.  To ensure that ABI compatibility is possible all exported symbols will be prefixed `LIMD_` to ensure in a 1 namespace model they do not conflict.

The libraries I've decided to extract so far are:
- JSON (jsmn.c)
- SHA1
- SHA2 (as sha512.c)
- Endianness
- FixedInt
- Locking

**Comment by XanaduAPI** [comment]
If you can, you'd better add MSVC compatible export.
@nikias 
What do you think?
