### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by likenow** [libimobiledevice/libimobiledevice-glue#6]
MacBook Pro (13-inch, M1, 2020)  11.5.2 (20G95)
Apple M1
iTerm2 Build 3.3.12

Configuration for libimobiledevice-glue 1.0.0:
-------------------------------------------

  Install prefix: .........: /usr/local

  Now type 'make' to build libimobiledevice-glue 1.0.0,
  and then 'make install' for installation.

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       glue.lo
  CC       socket.lo
  CC       thread.lo
  CC       utils.lo
  CC       collection.lo
  CC       termcolors.lo
  CCLD     libimobiledevice-glue-1.0.la
Undefined symbols for architecture x86_64:
  "_plist_array_get_item", referenced from:
      _plist_print_to_stream_with_indentation in utils.o
      _plist_node_print_to_stream in utils.o
  "_plist_array_get_size", referenced from:
      _plist_print_to_stream_with_indentation in utils.o
      _plist_dict_print_to_stream in utils.o
      _plist_node_print_to_stream in utils.o
  "_plist_dict_new_iter", referenced from:
      _plist_dict_print_to_stream in utils.o
  "_plist_dict_next_item", referenced from:
      _plist_dict_print_to_stream in utils.o
  "_plist_from_bin", referenced from:
      _plist_read_from_filename in utils.o
  "_plist_from_xml", referenced from:
      _plist_read_from_filename in utils.o
  "_plist_get_bool_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_data_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_date_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_key_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_node_type", referenced from:
      _plist_print_to_stream_with_indentation in utils.o
      _plist_dict_print_to_stream in utils.o
      _plist_node_print_to_stream in utils.o
  "_plist_get_real_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_string_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_get_uint_val", referenced from:
      _plist_node_print_to_stream in utils.o
  "_plist_to_bin", referenced from:
      _plist_write_to_filename in utils.o
  "_plist_to_xml", referenced from:
      _plist_write_to_filename in utils.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libimobiledevice-glue-1.0.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by jagdish24** [comment]
Have you found any solution? I am stuck at same.

**Comment by jkcoxson** [comment]
libplist was built incorrectly, it needs to be built and installed with an aarch64 toolchain
